/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBuscarRouteImport } from './routes/_authenticated/buscar'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as AuthenticatedClientesNovoRouteImport } from './routes/_authenticated/clientes.novo'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBuscarRoute = AuthenticatedBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesNovoRoute =
  AuthenticatedClientesNovoRouteImport.update({
    id: '/clientes/novo',
    path: '/clientes/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/buscar': typeof AuthenticatedBuscarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/buscar'
    | '/dashboard'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/buscar'
    | '/dashboard'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/clientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/buscar'
    | '/_authenticated/dashboard'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/clientes/novo'
    | '/_authenticated/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/buscar': {
      id: '/_authenticated/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof AuthenticatedBuscarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes/novo': {
      id: '/_authenticated/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AuthenticatedClientesNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBuscarRoute: typeof AuthenticatedBuscarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedClientesNovoRoute: typeof AuthenticatedClientesNovoRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBuscarRoute: AuthenticatedBuscarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedClientesNovoRoute: AuthenticatedClientesNovoRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
