/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedBuscarRouteImport } from './routes/_authenticated/buscar'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedProcessosIndexRouteImport } from './routes/_authenticated/processos.index'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as AuthenticatedProcessosNovoRouteImport } from './routes/_authenticated/processos.novo'
import { Route as AuthenticatedProcessosIdRouteImport } from './routes/_authenticated/processos.$id'
import { Route as AuthenticatedClientesNovoRouteImport } from './routes/_authenticated/clientes.novo'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBuscarRoute = AuthenticatedBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProcessosIndexRoute =
  AuthenticatedProcessosIndexRouteImport.update({
    id: '/processos/',
    path: '/processos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProcessosNovoRoute =
  AuthenticatedProcessosNovoRouteImport.update({
    id: '/processos/novo',
    path: '/processos/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProcessosIdRoute =
  AuthenticatedProcessosIdRouteImport.update({
    id: '/processos/$id',
    path: '/processos/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesNovoRoute =
  AuthenticatedClientesNovoRouteImport.update({
    id: '/clientes/novo',
    path: '/clientes/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/processos/novo': typeof AuthenticatedProcessosNovoRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/processos/': typeof AuthenticatedProcessosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/processos/novo': typeof AuthenticatedProcessosNovoRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/processos': typeof AuthenticatedProcessosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/buscar': typeof AuthenticatedBuscarRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/_authenticated/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/_authenticated/processos/novo': typeof AuthenticatedProcessosNovoRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/processos/': typeof AuthenticatedProcessosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auditoria'
    | '/buscar'
    | '/calendario'
    | '/dashboard'
    | '/tarefas'
    | '/usuarios'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/processos/$id'
    | '/processos/novo'
    | '/clientes/'
    | '/processos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auditoria'
    | '/buscar'
    | '/calendario'
    | '/dashboard'
    | '/tarefas'
    | '/usuarios'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/processos/$id'
    | '/processos/novo'
    | '/clientes'
    | '/processos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/auditoria'
    | '/_authenticated/buscar'
    | '/_authenticated/calendario'
    | '/_authenticated/dashboard'
    | '/_authenticated/tarefas'
    | '/_authenticated/usuarios'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/clientes/novo'
    | '/_authenticated/processos/$id'
    | '/_authenticated/processos/novo'
    | '/_authenticated/clientes/'
    | '/_authenticated/processos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/buscar': {
      id: '/_authenticated/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof AuthenticatedBuscarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/processos/': {
      id: '/_authenticated/processos/'
      path: '/processos'
      fullPath: '/processos/'
      preLoaderRoute: typeof AuthenticatedProcessosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/processos/novo': {
      id: '/_authenticated/processos/novo'
      path: '/processos/novo'
      fullPath: '/processos/novo'
      preLoaderRoute: typeof AuthenticatedProcessosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/processos/$id': {
      id: '/_authenticated/processos/$id'
      path: '/processos/$id'
      fullPath: '/processos/$id'
      preLoaderRoute: typeof AuthenticatedProcessosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes/novo': {
      id: '/_authenticated/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AuthenticatedClientesNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedBuscarRoute: typeof AuthenticatedBuscarRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedClientesNovoRoute: typeof AuthenticatedClientesNovoRoute
  AuthenticatedProcessosIdRoute: typeof AuthenticatedProcessosIdRoute
  AuthenticatedProcessosNovoRoute: typeof AuthenticatedProcessosNovoRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedProcessosIndexRoute: typeof AuthenticatedProcessosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedBuscarRoute: AuthenticatedBuscarRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedClientesNovoRoute: AuthenticatedClientesNovoRoute,
  AuthenticatedProcessosIdRoute: AuthenticatedProcessosIdRoute,
  AuthenticatedProcessosNovoRoute: AuthenticatedProcessosNovoRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedProcessosIndexRoute: AuthenticatedProcessosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
